# Generated by Django 4.2.16 on 2026-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
